services:
  - type: web
    name: armscale-backend
    runtime: python
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
